package com.corruptedstudio.activityafk;

import net.milkbowl.vault.chat.Chat;
import net.milkbowl.vault.economy.Economy;
import org.bukkit.*;
import org.bukkit.command.*;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.entity.EntityDamageEvent;
import org.bukkit.event.inventory.*;
import org.bukkit.event.player.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.RegisteredServiceProvider;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.File;
import java.sql.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAdjusters;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/** Production entry point. Persistent data is UTC epoch seconds; calendar cutovers use config timezone. */
public final class ActivityAFKPlugin extends JavaPlugin implements Listener, CommandExecutor, TabCompleter {
    private Connection db; private Economy economy; private Chat chat;
    private final Map<UUID, PlayerState> online = new ConcurrentHashMap<>();
    private final Map<UUID, Viewer> viewers = new ConcurrentHashMap<>(); private final Map<UUID,Integer> guiTasks = new ConcurrentHashMap<>();
    private final Map<String, Zone> zones = new LinkedHashMap<>(); private final Map<UUID, Location> pos1 = new HashMap<>(), pos2 = new HashMap<>();
    private FileConfiguration afk, rewards, messages; private Zone currentZone;
    private ZonePoint last1, last2;
    private enum Status { ACTIVE, AFK_MANUAL, AFK_AUTOMATIC, AFK_ZONE }
    private record PlayerState(UUID uuid,String name,long online, long active,long afk,long todayActive,long weekActive,long monthActive,long todayAfk,long weekAfk,long monthAfk,long action,Status status,String day,String week,String month) {}
    private record Zone(String id,String world,int minX,int maxX,int minY,int maxY,int minZ,int maxZ,boolean rewards,boolean protection) { boolean contains(Location l){return l.getWorld()!=null&&l.getWorld().getName().equals(world)&&l.getBlockX()>=minX&&l.getBlockX()<=maxX&&l.getBlockY()>=minY&&l.getBlockY()<=maxY&&l.getBlockZ()>=minZ&&l.getBlockZ()<=maxZ;} }
    private record ZonePoint(String world,int x,int y,int z) {}
    private record Viewer(UUID target,int normal,int detailed,String title) {}

    @Override public void onEnable() {
        saveDefaultConfig(); for(String f:new String[]{"afk.yml","rewards.yml","zones.yml","messages.yml"}) saveResource(f,false);
        afk=file("afk.yml"); rewards=file("rewards.yml"); messages=file("messages.yml"); openDb(); loadZones(); setupIntegrations();
        for(String n:List.of("info","detailinfo","guiinfo","afk","activity","afkzone")){PluginCommand c=getCommand(n); if(c!=null){c.setExecutor(this);c.setTabCompleter(this);}}
        getServer().getPluginManager().registerEvents(this,this); for(Player p:Bukkit.getOnlinePlayers()) login(p);
        Bukkit.getScheduler().runTaskTimer(this,this::tick,20L,20L); Bukkit.getScheduler().runTaskTimer(this,this::processWeekly,20L*30,20L*30);
        getLogger().info("ActivityAFK enabled; SQLite, active/AFK separation, rewards and tab completion are ready.");
    }
    private FileConfiguration file(String n){return org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(new File(getDataFolder(),n));}
    private void openDb(){try{getDataFolder().mkdirs();db=DriverManager.getConnection("jdbc:sqlite:"+new File(getDataFolder(),"activity.db"));try(Statement s=db.createStatement()){s.executeUpdate("PRAGMA busy_timeout=5000");s.executeUpdate("PRAGMA journal_mode=WAL");s.executeUpdate("CREATE TABLE IF NOT EXISTS players(uuid TEXT PRIMARY KEY,name TEXT NOT NULL,first_seen INTEGER NOT NULL,last_seen INTEGER NOT NULL,online INTEGER DEFAULT 0,active INTEGER DEFAULT 0,afk INTEGER DEFAULT 0,today_active INTEGER DEFAULT 0,week_active INTEGER DEFAULT 0,month_active INTEGER DEFAULT 0,today_afk INTEGER DEFAULT 0,week_afk INTEGER DEFAULT 0,month_afk INTEGER DEFAULT 0,prizes INTEGER DEFAULT 0,day TEXT,week TEXT,month TEXT)");s.executeUpdate("CREATE TABLE IF NOT EXISTS rewards(id TEXT PRIMARY KEY,week TEXT,uuid TEXT,name TEXT,position INTEGER,seconds INTEGER,status TEXT,commands TEXT,processed INTEGER DEFAULT 0)");s.executeUpdate("CREATE TABLE IF NOT EXISTS winners(id TEXT PRIMARY KEY,week TEXT,uuid TEXT,name TEXT,position INTEGER,seconds INTEGER,processed_at INTEGER)");s.executeUpdate("CREATE TABLE IF NOT EXISTS zones(id TEXT PRIMARY KEY,world TEXT,minx INTEGER,maxx INTEGER,miny INTEGER,maxy INTEGER,minz INTEGER,maxz INTEGER,rewards INTEGER,protection INTEGER)");}}catch(Exception e){throw new IllegalStateException("Unable to open SQLite",e);}}
    private void setupIntegrations(){if(getServer().getPluginManager().getPlugin("Vault")==null){getLogger().info("Vault not installed; balances will show unavailable.");return;}RegisteredServiceProvider<Economy> e=getServer().getServicesManager().getRegistration(Economy.class);if(e!=null)economy=e.getProvider();RegisteredServiceProvider<Chat> c=getServer().getServicesManager().getRegistration(Chat.class);if(c!=null)chat=c.getProvider();getLogger().info(economy==null?"No Vault economy provider found.":"Vault economy: "+economy.getName());}
    private Zone zone(Location l){for(Zone z:zones.values())if(z.contains(l))return z;return null;}
    private void loadZones(){try(PreparedStatement p=db.prepareStatement("SELECT * FROM zones")){ResultSet r=p.executeQuery();while(r.next())zones.put(r.getString(1),new Zone(r.getString(1),r.getString(2),r.getInt(3),r.getInt(4),r.getInt(5),r.getInt(6),r.getInt(7),r.getInt(8),r.getBoolean(9),r.getBoolean(10)));}catch(SQLException e){getLogger().warning(e.getMessage());}}
    private String today(){return LocalDate.now(zoneId()).toString();} private String month(){return YearMonth.now(zoneId()).toString();} private String week(){LocalDate d=LocalDate.now(zoneId());DayOfWeek reset=DayOfWeek.valueOf(getConfig().getString("schedule.week-reset.day","MONDAY").toUpperCase());return d.with(TemporalAdjusters.previousOrSame(reset)).toString();} private ZoneId zoneId(){try{return ZoneId.of(getConfig().getString("timezone","Asia/Kolkata"));}catch(Exception e){getLogger().warning("Invalid timezone; using UTC");return ZoneOffset.UTC;}}
    private void login(Player p){PlayerState s=read(p.getUniqueId(),p.getName());online.put(p.getUniqueId(),new PlayerState(s.uuid,p.getName(),s.online,s.active,s.afk,s.todayActive,s.weekActive,s.monthActive,s.todayAfk,s.weekAfk,s.monthAfk,System.currentTimeMillis()/1000,Status.ACTIVE,today(),week(),month())); claimPending(p);}
    private PlayerState read(UUID id,String name){try(PreparedStatement q=db.prepareStatement("SELECT * FROM players WHERE uuid=?")){q.setString(1,id.toString());ResultSet r=q.executeQuery();if(r.next())return new PlayerState(id,name,r.getLong("online"),r.getLong("active"),r.getLong("afk"),r.getLong("today_active"),r.getLong("week_active"),r.getLong("month_active"),r.getLong("today_afk"),r.getLong("week_afk"),r.getLong("month_afk"),System.currentTimeMillis()/1000,Status.ACTIVE,r.getString("day"),r.getString("week"),r.getString("month"));}catch(SQLException e){getLogger().warning(e.getMessage());}long n=System.currentTimeMillis()/1000;try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO players(uuid,name,first_seen,last_seen,day,week,month) VALUES(?,?,?,?,?,?,?)")){q.setString(1,id.toString());q.setString(2,name);q.setLong(3,n);q.setLong(4,n);q.setString(5,today());q.setString(6,week());q.setString(7,month());q.executeUpdate();}catch(SQLException e){getLogger().warning(e.getMessage());}return new PlayerState(id,name,0,0,0,0,0,0,0,0,0,n,Status.ACTIVE,today(),week(),month());}
    private void tick(){long now=System.currentTimeMillis()/1000;for(Player p:Bukkit.getOnlinePlayers()){PlayerState s=online.get(p.getUniqueId());if(s==null)continue;String d=today(),w=week(),m=month();long ta=s.todayActive,wa=s.weekActive,ma=s.monthActive,tf=s.todayAfk,wf=s.weekAfk,mf=s.monthAfk;if(!d.equals(s.day))ta=tf=0;if(!w.equals(s.week))wa=wf=0;if(!m.equals(s.month))ma=mf=0;Status st=s.status;Zone z=zone(p.getLocation());if(st==Status.ACTIVE&&getConfig().getBoolean("automatic-afk.enabled",true)&&now-s.action>=getConfig().getLong("automatic-afk.after-seconds",300))st=Status.AFK_AUTOMATIC;boolean af=st!=Status.ACTIVE;PlayerState n=new PlayerState(s.uuid,p.getName(),s.online+1,s.active+(af?0:1),s.afk+(af?1:0),ta+(af?0:1),wa+(af?0:1),ma+(af?0:1),tf+(af?1:0),wf+(af?1:0),mf+(af?1:0),s.action,st,d,w,m);online.put(p.getUniqueId(),n);save(n);if(st!=s.status)stateMessage(p,st);if(af&&z!=null&&z.rewards)rewardTick(p,n);}}
    private void save(PlayerState s){try(PreparedStatement q=db.prepareStatement("UPDATE players SET name=?,last_seen=?,online=?,active=?,afk=?,today_active=?,week_active=?,month_active=?,today_afk=?,week_afk=?,month_afk=?,day=?,week=?,month=? WHERE uuid=?")){int i=1;q.setString(i++,s.name);q.setLong(i++,System.currentTimeMillis()/1000);for(long v:new long[]{s.online,s.active,s.afk,s.todayActive,s.weekActive,s.monthActive,s.todayAfk,s.weekAfk,s.monthAfk})q.setLong(i++,v);q.setString(i++,s.day);q.setString(i++,s.week);q.setString(i++,s.month);q.setString(i,s.uuid.toString());q.executeUpdate();}catch(SQLException e){getLogger().warning("Save failed: "+e.getMessage());}}
    private void activity(Player p,boolean rotation){PlayerState s=online.get(p.getUniqueId());if(s==null)return;boolean enabled=rotation?getConfig().getBoolean("automatic-afk.camera-cancels",true):getConfig().getBoolean("automatic-afk.movement-cancels",true);if(enabled&&(s.status==Status.AFK_AUTOMATIC||s.status==Status.AFK_ZONE)){online.put(p.getUniqueId(),new PlayerState(s.uuid,s.name,s.online,s.active,s.afk,s.todayActive,s.weekActive,s.monthActive,s.todayAfk,s.weekAfk,s.monthAfk,System.currentTimeMillis()/1000,Status.ACTIVE,s.day,s.week,s.month));stateMessage(p,Status.ACTIVE);}else online.put(p.getUniqueId(),new PlayerState(s.uuid,s.name,s.online,s.active,s.afk,s.todayActive,s.weekActive,s.monthActive,s.todayAfk,s.weekAfk,s.monthAfk,System.currentTimeMillis()/1000,s.status,s.day,s.week,s.month));}
    private void stateMessage(Player p,Status s){if(s==Status.ACTIVE)message(p,"afk-exit",Map.of());else if(s!=Status.AFK_ZONE)message(p,"afk-enter",Map.of());}
    private void rewardTick(Player p,PlayerState s){long interval=afk.getLong("reward.interval-seconds",3600),max=afk.getLong("reward.max-reward-time-seconds",14400);if(!afk.getBoolean("reward.enabled",false)||interval<=0||s.afk>max||s.afk%interval!=0||s.afk/interval>afk.getLong("reward.daily-limit",4)||p.hasPermission("activity.afk.reward.bypass"))return;for(String c:afk.getStringList("reward.commands"))Bukkit.dispatchCommand(Bukkit.getConsoleSender(),replace(c,p,s,0,s.week));message(p,"reward",Map.of());}
    @EventHandler public void onJoin(PlayerJoinEvent e){login(e.getPlayer());}@EventHandler public void onQuit(PlayerQuitEvent e){PlayerState s=online.remove(e.getPlayer().getUniqueId());if(s!=null)save(s);closeGui(e.getPlayer());}
    @EventHandler public void onMove(PlayerMoveEvent e){if(e.getTo()==null)return;activity(e.getPlayer(),e.getFrom().getYaw()!=e.getTo().getYaw()||e.getFrom().getPitch()!=e.getTo().getPitch());Zone z=zone(e.getTo());PlayerState s=online.get(e.getPlayer().getUniqueId());if(s!=null&&z!=null&&s.status==Status.ACTIVE)online.put(s.uuid,new PlayerState(s.uuid,s.name,s.online,s.active,s.afk,s.todayActive,s.weekActive,s.monthActive,s.todayAfk,s.weekAfk,s.monthAfk,s.action,Status.AFK_ZONE,s.day,s.week,s.month));else if(s!=null&&z==null&&s.status==Status.AFK_ZONE)activity(e.getPlayer(),false);}
    @EventHandler public void damage(EntityDamageEvent e){if(!(e.getEntity() instanceof Player p)||p.hasPermission("activity.afk.protection.bypass"))return;PlayerState s=online.get(p.getUniqueId());if(s==null||s.status==Status.ACTIVE||!afk.getBoolean("protection.enabled",true))return;if(afk.getBoolean("protection.damage",true))e.setCancelled(true);}
    @EventHandler public void breakBlock(BlockBreakEvent e){if(blockProtected(e.getPlayer(),e.getBlock().getLocation())&&afk.getBoolean("block-protection.block-break",true))e.setCancelled(true);}
    @EventHandler public void placeBlock(BlockPlaceEvent e){if(blockProtected(e.getPlayer(),e.getBlock().getLocation())&&afk.getBoolean("block-protection.block-place",true))e.setCancelled(true);}
    private boolean blockProtected(Player actor,Location l){if(actor.hasPermission("activity.afk.protection.bypass")||!afk.getBoolean("block-protection.enabled",true))return false;int r=afk.getInt("block-protection.radius",2);for(Player p:Bukkit.getOnlinePlayers()){PlayerState s=online.get(p.getUniqueId());if(s!=null&&s.status!=Status.ACTIVE&&p.getWorld().equals(l.getWorld())&&p.getLocation().distanceSquared(l)<=r*r)return true;}return false;}
    @EventHandler public void click(InventoryClickEvent e){if(e.getWhoClicked() instanceof Player p&&viewers.containsKey(p.getUniqueId()))e.setCancelled(true);}@EventHandler public void drag(InventoryDragEvent e){if(e.getWhoClicked() instanceof Player p&&viewers.containsKey(p.getUniqueId()))e.setCancelled(true);}@EventHandler public void close(InventoryCloseEvent e){if(e.getPlayer() instanceof Player p)closeGui(p);}
    private void closeGui(Player p){viewers.remove(p.getUniqueId());Integer id=guiTasks.remove(p.getUniqueId());if(id!=null)Bukkit.getScheduler().cancelTask(id);}
    private String duration(long x){long h=x/3600,m=x%3600/60,s=x%60;return h>0?h+"h "+m+"m "+s+"s":m>0?m+"m "+s+"s":s+"s";}
    private String rank(Player p){return chat==null?"Member":Optional.ofNullable(chat.getPlayerPrefix(p)).filter(x->!x.isBlank()).orElse("Member");}
    private String money(Player p){return economy==null?"Unavailable":String.format("%,.2f",economy.getBalance(p));}
    private void show(CommandSender sender,Player target,PlayerState s,boolean detail){sender.sendMessage("§6===== "+(detail?"DETAILED ":"")+"PLAYER INFORMATION =====");sender.sendMessage("§fName: §e"+target.getName()+" §fRank: §e"+rank(target));sender.sendMessage("§fUUID: §7"+target.getUniqueId());sender.sendMessage("§fRegistered/Last Seen: §7"+(target.isOnline()?"Currently Online":"stored in SQLite"));sender.sendMessage("§6Active §fToday "+duration(s.todayActive)+" | Week "+duration(s.weekActive)+" | Month "+duration(s.monthActive)+" | Total "+duration(s.active));if(detail)sender.sendMessage("§6AFK §fToday "+duration(s.todayAfk)+" | Week "+duration(s.weekAfk)+" | Month "+duration(s.monthAfk)+" | Total "+duration(s.afk));sender.sendMessage("§fBalance: §e"+money(target));}
    private void gui(Player viewer,Player target,PlayerState s){int size=Math.max(9,Math.min(54,getConfig().getInt("gui.size",9)));String title=color(getConfig().getString("gui.title","&8Player Information: &e[player]")).replace("[player]",target.getName());Inventory inv=Bukkit.createInventory(null,size,title);int n=getConfig().getInt("gui.normal-info.slot",3),d=getConfig().getInt("gui.detailed-info.slot",5);viewers.put(viewer.getUniqueId(),new Viewer(target.getUniqueId(),n,d,title));updateGui(viewer,inv,s);viewer.openInventory(inv);long ticks=Math.max(1,getConfig().getLong("gui.refresh-interval-ticks",1));int task=Bukkit.getScheduler().runTaskTimer(this,()->{Viewer v=viewers.get(viewer.getUniqueId());if(v==null||!viewer.isOnline()||!viewer.getOpenInventory().getTitle().equals(v.title)){closeGui(viewer);return;}updateGui(viewer,viewer.getOpenInventory().getTopInventory(),online.getOrDefault(v.target,read(v.target,target.getName())));},ticks,ticks).getTaskId();guiTasks.put(viewer.getUniqueId(),task);}
    private void updateGui(Player p,Inventory inv,PlayerState s){Viewer v=viewers.get(p.getUniqueId());if(v==null)return;ItemStack a=item(Material.BOOK,"gui.normal-info",List.of("§fName: "+s.name,"§fRank: "+rank(p),"§fToday: "+duration(s.todayActive),"§fWeek: "+duration(s.weekActive),"§fMonth: "+duration(s.monthActive),"§fTotal: "+duration(s.active),"§fBalance: "+money(p)));ItemStack b=item(Material.WRITABLE_BOOK,"gui.detailed-info",List.of("§fName: "+s.name,"§fUUID: "+s.uuid,"§6Playtime","§fToday: "+duration(s.todayActive),"§fWeek: "+duration(s.weekActive),"§fMonth: "+duration(s.monthActive),"§fTotal: "+duration(s.active),"§6AFK","§fToday: "+duration(s.todayAfk),"§fWeek: "+duration(s.weekAfk),"§fMonth: "+duration(s.monthAfk),"§fTotal: "+duration(s.afk)));if(v.normal<inv.getSize())inv.setItem(v.normal,a);if(v.detailed<inv.getSize())inv.setItem(v.detailed,b);}
    private ItemStack item(Material fallback,String path,List<String> lore){Material m;try{m=Material.valueOf(getConfig().getString(path+".material",fallback.name()).toUpperCase());}catch(Exception e){m=fallback;}ItemStack i=new ItemStack(m);ItemMeta meta=i.getItemMeta();meta.setDisplayName(color(getConfig().getString(path+".name","&eInformation")));meta.setLore(lore);i.setItemMeta(meta);return i;}
    private void leaderboard(CommandSender s){List<PlayerState> all=new ArrayList<>(online.values());all.sort(Comparator.comparingLong(PlayerState::weekActive).reversed().thenComparing(x->x.uuid.toString()));s.sendMessage("§6===== WEEKLY ACTIVITY =====");int n=1;for(PlayerState p:all.subList(0,Math.min(all.size(),getConfig().getInt("leaderboard-size",10))))s.sendMessage("§e"+n+++". §f"+p.name+" §7"+duration(p.weekActive));}
    private void processWeekly(){/* Idempotent reward records are created by week key; delivery is retried on join. */String w=week();try(PreparedStatement q=db.prepareStatement("SELECT 1 FROM rewards WHERE week=? LIMIT 1")){q.setString(1,w);if(q.executeQuery().next())return;}catch(SQLException ignored){}List<PlayerState> list=new ArrayList<>(online.values());list.sort(Comparator.comparingLong(PlayerState::weekActive).reversed().thenComparing(x->x.uuid.toString()));int last=-1;long prior=-1;for(int i=0;i<list.size();i++){PlayerState s=list.get(i);int pos=s.weekActive==prior?last:i+1;last=pos;prior=s.weekActive;List<String> commands=rewards.getStringList("weekly-rewards."+pos+".commands");if(commands.isEmpty())continue;String id=w+":"+s.uuid+":"+pos;try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO rewards VALUES(?,?,?,?,?,?,?,?,?,?)")){q.setString(1,id);q.setString(2,w);q.setString(3,s.uuid.toString());q.setString(4,s.name);q.setInt(5,pos);q.setLong(6,s.weekActive);q.setString(7,"PENDING");q.setString(8,String.join("\n",commands));q.setInt(9,0);q.executeUpdate();}catch(SQLException e){getLogger().warning(e.getMessage());}}}
    private void claimPending(Player p){try(PreparedStatement q=db.prepareStatement("SELECT * FROM rewards WHERE uuid=? AND status='PENDING'")){q.setString(1,p.getUniqueId().toString());ResultSet r=q.executeQuery();while(r.next()){for(String c:r.getString("commands").split("\\n"))Bukkit.dispatchCommand(Bukkit.getConsoleSender(),replace(c,p,online.get(p.getUniqueId()),r.getInt("position"),r.getString("week")));try(PreparedStatement u=db.prepareStatement("UPDATE rewards SET status='CLAIMED',processed=1 WHERE id=? AND status='PENDING'")){u.setString(1,r.getString("id"));u.executeUpdate();}catch(SQLException ignored){}message(p,"weekly-reward",Map.of("week",r.getString("week")));}}catch(SQLException e){getLogger().warning(e.getMessage());}}
    private String replace(String x,Player p,PlayerState s,int pos,String w){return x.replace("[player]",p.getName()).replace("[uuid]",p.getUniqueId().toString()).replace("[rank]",rank(p)).replace("[balance]",money(p)).replace("[playtime]",duration(s.active)).replace("[playtime_today]",duration(s.todayActive)).replace("[playtime_week]",duration(s.weekActive)).replace("[playtime_month]",duration(s.monthActive)).replace("[playtime_total]",duration(s.active)).replace("[afk_today]",duration(s.todayAfk)).replace("[afk_week]",duration(s.weekAfk)).replace("[afk_month]",duration(s.monthAfk)).replace("[afk_total]",duration(s.afk)).replace("[position]",String.valueOf(pos)).replace("[week]",w);}
    private void message(CommandSender s,String key,Map<String,String> values){String x=messages.getString(key,key);for(var e:values.entrySet())x=x.replace("["+e.getKey()+"]",e.getValue());s.sendMessage(color(messages.getString("prefix","")+x));}private String color(String s){return ChatColor.translateAlternateColorCodes('&',s==null?"":s);}
    @Override public boolean onCommand(CommandSender s,Command c,String l,String[] a){String n=c.getName().toLowerCase();if(n.equals("afk")){if(!(s instanceof Player p)){message(s,"player-only",Map.of());return true;}PlayerState x=online.get(p.getUniqueId());if(x!=null){Status next=x.status==Status.ACTIVE?Status.AFK_MANUAL:Status.ACTIVE;online.put(p.getUniqueId(),new PlayerState(x.uuid,x.name,x.online,x.active,x.afk,x.todayActive,x.weekActive,x.monthActive,x.todayAfk,x.weekAfk,x.monthAfk,System.currentTimeMillis()/1000,next,x.day,x.week,x.month));stateMessage(p,next);}return true;}if(n.equals("info")||n.equals("detailinfo")||n.equals("guiinfo")){Player target=a.length==0&&s instanceof Player?(Player)s:Bukkit.getPlayerExact(a.length>0?a[0]:"");if(target==null){message(s,"player-not-found",Map.of());return true;}PlayerState x=online.getOrDefault(target.getUniqueId(),read(target.getUniqueId(),target.getName()));if(n.equals("guiinfo")&&s instanceof Player p)gui(p,target,x);else show(s,target,x,n.equals("detailinfo"));return true;}if(n.equals("activity")){if(a.length==0||a[0].equalsIgnoreCase("top")){leaderboard(s);return true;}if(a[0].equalsIgnoreCase("reload")){reloadConfig();afk=file("afk.yml");rewards=file("rewards.yml");messages=file("messages.yml");message(s,"reset",Map.of());return true;}if(a[0].equalsIgnoreCase("winners")){s.sendMessage("§6Previous winners are persisted in plugins/ActivityAFK/activity.db.");return true;}if(a[0].equalsIgnoreCase("resetweek")){try(db.createStatement().executeUpdate("UPDATE players SET week_active=0,week_afk=0"));catch(SQLException ignored){}message(s,"reset",Map.of());return true;}if(a[0].equalsIgnoreCase("reset")&&a.length>1){OfflinePlayer p=Bukkit.getOfflinePlayer(a[1]);try(PreparedStatement q=db.prepareStatement("UPDATE players SET active=0,afk=0,online=0,today_active=0,week_active=0,month_active=0,today_afk=0,week_afk=0,month_afk=0 WHERE uuid=?")){q.setString(1,p.getUniqueId().toString());q.executeUpdate();}catch(SQLException ignored){}message(s,"reset",Map.of());return true;}}if(n.equals("afkzone"))return zones(s,a);return true;}
    private boolean zones(CommandSender s,String[] a){if(a.length==0){s.sendMessage("§e/afkzone <create|delete|list|info|setpos1|setpos2|setreward|setprotection> <name>");return true;}String sub=a[0].toLowerCase();if(sub.equals("list")){s.sendMessage("§6Zones: §f"+String.join(", ",zones.keySet()));return true;}if(a.length<2)return true;String id=a[1];if(sub.equals("create")){saveZone(new Zone(id,"world",0,0,0,0,0,0,true,true));}else if(sub.equals("delete")){zones.remove(id);try(PreparedStatement q=db.prepareStatement("DELETE FROM zones WHERE id=?")){q.setString(1,id);q.executeUpdate();}catch(SQLException ignored){}}else if((sub.equals("setpos1")||sub.equals("setpos2"))&&s instanceof Player p){ZonePoint v=new ZonePoint(p.getWorld().getName(),p.getLocation().getBlockX(),p.getLocation().getBlockY(),p.getLocation().getBlockZ());if(sub.endsWith("1"))last1=v;else last2=v;if(last1!=null&&last2!=null)saveZone(new Zone(id,last1.world,Math.min(last1.x,last2.x),Math.max(last1.x,last2.x),Math.min(last1.y,last2.y),Math.max(last1.y,last2.y),Math.min(last1.z,last2.z),Math.max(last1.z,last2.z),true,true));}else if(a.length>2&&(sub.equals("setreward")||sub.equals("setprotection"))){Zone z=zones.get(id);if(z!=null){boolean v=Boolean.parseBoolean(a[2]);saveZone(new Zone(z.id,z.world,z.minX,z.maxX,z.minY,z.maxY,z.minZ,z.maxZ,sub.equals("setreward")?v:z.rewards,sub.equals("setprotection")?v:z.protection));}}return true;}
    private void saveZone(Zone z){zones.put(z.id,z);try(PreparedStatement q=db.prepareStatement("INSERT OR REPLACE INTO zones VALUES(?,?,?,?,?,?,?,?,?,?)")){q.setString(1,z.id);q.setString(2,z.world);q.setInt(3,z.minX);q.setInt(4,z.maxX);q.setInt(5,z.minY);q.setInt(6,z.maxY);q.setInt(7,z.minZ);q.setInt(8,z.maxZ);q.setBoolean(9,z.rewards);q.setBoolean(10,z.protection);q.executeUpdate();}catch(SQLException e){getLogger().warning(e.getMessage());}}
    @Override public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){String n=c.getName().toLowerCase();if(List.of("info","detailinfo","guiinfo").contains(n)&&a.length==1)return players(a[0]);if(n.equals("activity")){if(a.length==1)return complete(a[0],List.of("top","winners","reload","reset","resetweek","forcewin"));if(a.length==2)return players(a[1]);}if(n.equals("afkzone")){if(a.length==1)return complete(a[0],List.of("create","delete","list","info","setpos1","setpos2","setreward","setprotection"));if(a.length==2)return complete(a[1],zones.keySet());if(a.length==3)return complete(a[2],List.of("true","false"));}return List.of();}
    private List<String> players(String x){List<String> r=new ArrayList<>();for(Player p:Bukkit.getOnlinePlayers())if(p.getName().toLowerCase().startsWith(x.toLowerCase()))r.add(p.getName());return r;}private List<String> complete(String x,Collection<String> all){return all.stream().filter(v->v.toLowerCase().startsWith(x.toLowerCase())).toList();}
    @Override public void onDisable(){for(PlayerState s:online.values())save(s);for(Player p:Bukkit.getOnlinePlayers())closeGui(p);try{if(db!=null)db.close();}catch(SQLException ignored){}}
}
