package com.corruptedstudio.activityafk;

import net.milkbowl.vault.economy.Economy;
import net.milkbowl.vault.chat.Chat;
import org.bukkit.*;
import org.bukkit.command.*;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.entity.EntityDamageEvent;
import org.bukkit.event.inventory.*;
import org.bukkit.event.player.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.RegisteredServiceProvider;
import org.bukkit.plugin.java.JavaPlugin;
import java.io.File;
import java.sql.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

public final class ActivityAFKPlugin extends JavaPlugin implements Listener, CommandExecutor, TabCompleter {
  private Connection db; private final Map<UUID, Session> sessions=new ConcurrentHashMap<>(); private final Map<UUID, Gui> guis=new HashMap<>(); private final Map<String,Zone> zones=new LinkedHashMap<>(); private Economy economy; private Chat chat; private ZonePos p1,p2;
  private FileConfiguration afk,rewards,zonesConfig,messages; private ZoneManager zoneManager;
  record Session(UUID id,String name,long online, long active,long afk,long todayActive,long weekActive,long monthActive,long todayAfk,long weekAfk,long monthAfk,long joined,long lastAction,State state){ Session with(State s){return new Session(id,name,online,active,afk,todayActive,weekActive,monthActive,todayAfk,weekAfk,monthAfk,joined,lastAction,s);} }
  enum State {ACTIVE,AFK_MANUAL,AFK_ZONE,AFK_AUTOMATIC}
  record Zone(String name,String world,int minX,int maxX,int minY,int maxY,int minZ,int maxZ,boolean rewards,boolean protection){ boolean contains(Location l){return l.getWorld()!=null&&l.getWorld().getName().equals(world)&&l.getBlockX()>=minX&&l.getBlockX()<=maxX&&l.getBlockY()>=minY&&l.getBlockY()<=maxY&&l.getBlockZ()>=minZ&&l.getBlockZ()<=maxZ;} }
  record ZonePos(String world,int x,int y,int z){}
  record Gui(UUID viewer,UUID target,int size,String title,int normal,int detailed){}
  @Override public void onEnable(){ saveDefaultConfig(); saveResource("afk.yml",false);saveResource("rewards.yml",false);saveResource("zones.yml",false);saveResource("messages.yml",false); afk=load("afk.yml");rewards=load("rewards.yml");zonesConfig=load("zones.yml");messages=load("messages.yml"); initDb();loadZones();setupVault();register(); for(Player p:Bukkit.getOnlinePlayers()) join(p); Bukkit.getScheduler().runTaskTimer(this,()->tick(),20,20); getLogger().info("ActivityAFK enabled with SQLite storage; timezone "+tz()); }
  private FileConfiguration load(String n){return org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(new File(getDataFolder(),n));}
  private void initDb(){try{if(!getDataFolder().exists())getDataFolder().mkdirs();db=DriverManager.getConnection("jdbc:sqlite:"+new File(getDataFolder(),"activity.db"));try(Statement s=db.createStatement()){s.executeUpdate("CREATE TABLE IF NOT EXISTS players(uuid TEXT PRIMARY KEY,name TEXT,first_seen INTEGER,last_seen INTEGER,online INTEGER DEFAULT 0,active INTEGER DEFAULT 0,afk INTEGER DEFAULT 0,today_active INTEGER DEFAULT 0,week_active INTEGER DEFAULT 0,month_active INTEGER DEFAULT 0,today_afk INTEGER DEFAULT 0,week_afk INTEGER DEFAULT 0,month_afk INTEGER DEFAULT 0,prizes INTEGER DEFAULT 0)");s.executeUpdate("CREATE TABLE IF NOT EXISTS winners(id TEXT PRIMARY KEY,week TEXT,uuid TEXT,name TEXT,position INTEGER,seconds INTEGER,status TEXT,commands TEXT)");s.executeUpdate("CREATE TABLE IF NOT EXISTS zones(name TEXT PRIMARY KEY,world TEXT,minx INTEGER,maxx INTEGER,miny INTEGER,maxy INTEGER,minz INTEGER,maxz INTEGER,rewards INTEGER,protection INTEGER)");}}catch(Exception e){getLogger().log(java.util.logging.Level.SEVERE,"Cannot open SQLite",e);}}
  private void loadZones(){try(PreparedStatement q=db.prepareStatement("SELECT * FROM zones")){ResultSet r=q.executeQuery();while(r.next())zones.put(r.getString(1),new Zone(r.getString(1),r.getString(2),r.getInt(3),r.getInt(4),r.getInt(5),r.getInt(6),r.getInt(7),r.getInt(8),r.getBoolean(9),r.getBoolean(10)));}catch(Exception ignored){} if(zones.isEmpty()&&zonesConfig.isConfigurationSection("zones"))for(String n:zonesConfig.getConfigurationSection("zones").getKeys(false)){} }
  private void setupVault(){if(getServer().getPluginManager().getPlugin("Vault")==null)return;RegisteredServiceProvider<Economy> e=getServer().getServicesManager().getRegistration(Economy.class);if(e!=null)economy=e.getProvider();RegisteredServiceProvider<Chat> c=getServer().getServicesManager().getRegistration(Chat.class);if(c!=null)chat=c.getProvider();getLogger().info(economy==null?"No Vault economy detected; balances unavailable.":"Vault economy detected: "+economy.getName());}
  private void register(){for(String n:new String[]{"info","detailinfo","guiinfo","afk","activity","afkzone"}){PluginCommand c=getCommand(n);c.setExecutor(this);c.setTabCompleter(this);}getServer().getPluginManager().registerEvents(this,this);}
  private Zone findZone(Location l){for(Zone z:zones.values())if(z.contains(l))return z;return null;}
  private void join(Player p){Session s=load(p.getUniqueId(),p.getName());sessions.put(p.getUniqueId(),s.with(State.ACTIVE)); String pending="SELECT id,week FROM winners WHERE uuid=? AND status='PENDING'";try(PreparedStatement q=db.prepareStatement(pending)){q.setString(1,p.getUniqueId().toString());ResultSet r=q.executeQuery();while(r.next()){dispatchWinner(p,r.getString(1));msg(p,"weekly-reward",Map.of("week",r.getString(2)));}}catch(Exception e){getLogger().warning(e.getMessage());}}
  private Session load(UUID id,String name){try(PreparedStatement q=db.prepareStatement("SELECT * FROM players WHERE uuid=?")){q.setString(1,id.toString());ResultSet r=q.executeQuery();if(r.next())return new Session(id,name,r.getLong("online"),r.getLong("active"),r.getLong("afk"),r.getLong("today_active"),r.getLong("week_active"),r.getLong("month_active"),r.getLong("today_afk"),r.getLong("week_afk"),r.getLong("month_afk"),System.currentTimeMillis()/1000,System.currentTimeMillis()/1000,State.ACTIVE);}catch(Exception ignored){}try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO players(uuid,name,first_seen,last_seen) VALUES(?,?,?,?)")){long now=System.currentTimeMillis()/1000;q.setString(1,id.toString());q.setString(2,name);q.setLong(3,now);q.setLong(4,now);q.executeUpdate();}catch(Exception e){getLogger().warning(e.getMessage());}return new Session(id,name,0,0,0,0,0,0,0,0,0,System.currentTimeMillis()/1000,System.currentTimeMillis()/1000,State.ACTIVE);}
  private void tick(){long now=System.currentTimeMillis()/1000;for(Player p:Bukkit.getOnlinePlayers()){Session s=sessions.get(p.getUniqueId());if(s==null)continue;State st=s.state;Zone z=findZone(p.getLocation());if(st==State.ACTIVE&&getConfig().getBoolean("automatic-afk.enabled",true)&&now-s.lastAction>=getConfig().getLong("automatic-afk.after-seconds",300))st=State.AFK_AUTOMATIC;if(st==State.AFK_AUTOMATIC&&z==null&&now-s.lastAction<2)st=State.ACTIVE;long on=s.online+1;boolean isAfk=st!=State.ACTIVE;Session n=new Session(s.id,p.getName(),on,s.active+(isAfk?0:1),s.afk+(isAfk?1:0),s.todayActive+(isAfk?0:1),s.weekActive+(isAfk?0:1),s.monthActive+(isAfk?0:1),s.todayAfk+(isAfk?1:0),s.weekAfk+(isAfk?1:0),s.monthAfk+(isAfk?1:0),s.joined, s.lastAction,st);sessions.put(p.getUniqueId(),n);save(n);if(st!=s.state)announceState(p,st);if(isAfk&&afk.getBoolean("reward.enabled",false))rewardTick(p,n,z);}}
  private void save(Session s){try(PreparedStatement q=db.prepareStatement("UPDATE players SET name=?,last_seen=?,online=?,active=?,afk=?,today_active=?,week_active=?,month_active=?,today_afk=?,week_afk=?,month_afk=? WHERE uuid=?")){int i=1;q.setString(i++,s.name);q.setLong(i++,System.currentTimeMillis()/1000);for(long v:new long[]{s.online,s.active,s.afk,s.todayActive,s.weekActive,s.monthActive,s.todayAfk,s.weekAfk,s.monthAfk})q.setLong(i++,v);q.setString(i,s.id.toString());q.executeUpdate();}catch(Exception e){getLogger().warning("Could not save player: "+e.getMessage());}}
  private void rewardTick(Player p,Session s,Zone z){if(z!=null&&!z.rewards)return;if(p.hasPermission("activity.afk.reward.bypass"))return;long interval=afk.getLong("reward.interval-seconds",3600),max=afk.getLong("reward.max-reward-time-seconds",14400);if(interval<=0||s.afk>max||s.afk%interval!=0)return;int count=(int)(s.afk/interval);if(count>afk.getInt("reward.daily-limit",4))return;for(String c:afk.getStringList("reward.commands"))Bukkit.dispatchCommand(Bukkit.getConsoleSender(),place(c,p,s,0,"AFK"));msg(p,"reward",Map.of());}
  private void announceState(Player p,State st){if(st==State.ACTIVE)msg(p,"afk-exit",Map.of());else if(st==State.AFK_MANUAL||st==State.AFK_AUTOMATIC)msg(p,"afk-enter",Map.of());}
  private void activity(Player p,boolean camera){Session s=sessions.get(p.getUniqueId());if(s==null)return;boolean cancel=getConfig().getBoolean(camera?"automatic-afk.camera-cancels":"automatic-afk.movement-cancels",true);if(cancel&&s.state!=State.ACTIVE){sessions.put(p.getUniqueId(),s.with(State.ACTIVE));announceState(p,State.ACTIVE);}sessions.put(p.getUniqueId(),new Session(s.id,s.name,s.online,s.active,s.afk,s.todayActive,s.weekActive,s.monthActive,s.todayAfk,s.weekAfk,s.monthAfk,System.currentTimeMillis()/1000,System.currentTimeMillis()/1000,s.state==State.ACTIVE?State.ACTIVE:s.state));}
  @EventHandler public void join(PlayerJoinEvent e){join(e.getPlayer());}
  @EventHandler public void quit(PlayerQuitEvent e){Session s=sessions.remove(e.getPlayer().getUniqueId());if(s!=null)save(s);}
  @EventHandler public void move(PlayerMoveEvent e){if(e.getTo()==null)return;activity(e.getPlayer(),e.getFrom().getYaw()!=e.getTo().getYaw()||e.getFrom().getPitch()!=e.getTo().getPitch());Zone z=findZone(e.getTo());Session s=sessions.get(e.getPlayer().getUniqueId());if(z!=null&&s!=null&&s.state==State.ACTIVE){sessions.put(e.getPlayer().getUniqueId(),s.with(State.AFK_ZONE));announceState(e.getPlayer(),State.AFK_ZONE);}if(z==null&&s!=null&&s.state==State.AFK_ZONE){sessions.put(e.getPlayer().getUniqueId(),s.with(State.ACTIVE));announceState(e.getPlayer(),State.ACTIVE);}}
  @EventHandler public void damage(EntityDamageEvent e){if(!(e.getEntity() instanceof Player p))return;Session s=sessions.get(p.getUniqueId());if(s==null||s.state==State.ACTIVE||p.hasPermission("activity.afk.protection.bypass")||!afk.getBoolean("protection.enabled",true))return;String k=e.getCause().name().toLowerCase(Locale.ROOT);if(afk.getBoolean("protection.damage",true)&&((k.contains("fall")&&afk.getBoolean("protection.fall",true))||(k.contains("fire")&&afk.getBoolean("protection.fire",true))||(k.contains("lava")&&afk.getBoolean("protection.lava",true))||(k.contains("drown")&&afk.getBoolean("protection.drowning",true))||(k.contains("projectile")&&afk.getBoolean("protection.projectile",true))||(k.contains("food")&&afk.getBoolean("protection.hunger",true))||(!k.contains("fall")&&!k.contains("fire")&&!k.contains("lava")&&!k.contains("drown")&&!k.contains("projectile")&&!k.contains("food"))))e.setCancelled(true);}
  @EventHandler public void click(InventoryClickEvent e){if(e.getWhoClicked() instanceof Player p&&guis.containsKey(p.getUniqueId()))e.setCancelled(true);}
  @EventHandler public void drag(InventoryDragEvent e){if(e.getWhoClicked() instanceof Player p&&guis.containsKey(p.getUniqueId()))e.setCancelled(true);}
  @EventHandler public void close(InventoryCloseEvent e){if(e.getPlayer() instanceof Player p)guis.remove(p.getUniqueId());}
  @EventHandler public void interact(PlayerInteractEvent e){activity(e.getPlayer(),false);}
  @Override public boolean onCommand(CommandSender sender,Command cmd,String label,String[] a){String n=cmd.getName().toLowerCase();if(n.equals("afk")){if(!(sender instanceof Player p)){msg(sender,"player-only",Map.of());return true;}Session s=sessions.get(p.getUniqueId());if(s!=null)sessions.put(p.getUniqueId(),s.with(s.state==State.ACTIVE?State.AFK_MANUAL:State.ACTIVE));return true;}if(n.equals("info")||n.equals("detailinfo")||n.equals("guiinfo")){Player target=sender instanceof Player p?p:null;if(a.length>0)target=Bukkit.getPlayerExact(a[0]);if(target==null){msg(sender,"player-not-found",Map.of());return true;}Session s=sessions.get(target.getUniqueId());if(s==null)s=load(target.getUniqueId(),target.getName());if(n.equals("guiinfo"))openGui((Player)sender,target,s);else print(sender,target,s,n.equals("detailinfo"));return true;}if(n.equals("activity")){if(a.length==0||a[0].equalsIgnoreCase("top")){top(sender);return true;}if(a[0].equalsIgnoreCase("winners")){sender.sendMessage("§6Previous winners are stored in SQLite; use the database for audit history.");return true;}if(a[0].equalsIgnoreCase("reload")){reloadConfig();afk=load("afk.yml");rewards=load("rewards.yml");zonesConfig=load("zones.yml");messages=load("messages.yml");msg(sender,"reset",Map.of());return true;}if(a[0].equalsIgnoreCase("reset")&&a.length>1){OfflinePlayer p=Bukkit.getOfflinePlayer(a[1]);try(PreparedStatement q=db.prepareStatement("UPDATE players SET online=0,active=0,afk=0,today_active=0,week_active=0,month_active=0,today_afk=0,week_afk=0,month_afk=0 WHERE uuid=?")){q.setString(1,p.getUniqueId().toString());q.executeUpdate();}catch(Exception ignored){}msg(sender,"reset",Map.of());return true;}}if(n.equals("afkzone"))return zoneCommand(sender,a);return true;}
  private void print(CommandSender o,Player p,Session s,boolean detail){String rank=rank(p),bal=economy==null?"Unavailable":String.format("%,.2f",economy.getBalance(p));o.sendMessage("§6===== "+(detail?"DETAILED ":"")+"PLAYER INFORMATION =====");o.sendMessage("§fName: §e"+p.getName()+" §fRank: §e"+rank);o.sendMessage("§fUUID: §7"+p.getUniqueId());o.sendMessage("§fRegistered/Last Seen: §7stored in SQLite");o.sendMessage("§6Active §fToday "+dur(s.todayActive)+" | Week "+dur(s.weekActive)+" | Month "+dur(s.monthActive)+" | Total "+dur(s.active));o.sendMessage("§6AFK §fToday "+dur(s.todayAfk)+" | Week "+dur(s.weekAfk)+" | Month "+dur(s.monthAfk)+" | Total "+dur(s.afk));o.sendMessage("§fOnline: "+dur(s.online)+" §fBalance: §e"+bal);}
  private void top(CommandSender o){List<Session> l=new ArrayList<>(sessions.values());l.sort(Comparator.comparingLong(Session::weekActive).reversed());o.sendMessage("§6===== WEEKLY ACTIVITY =====");int i=1;for(Session s:l.subList(0,Math.min(getConfig().getInt("leaderboard-size",10),l.size())))o.sendMessage("§e"+(i++)+". §f"+s.name+" §7"+dur(s.weekActive));}
  private void openGui(Player viewer,Player target,Session s){if(!getConfig().getBoolean("gui.enabled",true))return;int size=Math.max(9,Math.min(54,getConfig().getInt("gui.size",9)));String title=color(getConfig().getString("gui.title","&8Player Information: &e[player]")).replace("[player]",target.getName());Inventory inv=Bukkit.createInventory(null,size,title);Gui g=new Gui(viewer.getUniqueId(),target.getUniqueId(),size,title,getConfig().getInt("gui.normal-info.slot",3),getConfig().getInt("gui.detailed-info.slot",5));guis.put(viewer.getUniqueId(),g);updateGui(viewer,target,s,inv);viewer.openInventory(inv);Bukkit.getScheduler().runTaskTimer(this,()->{if(!guis.containsKey(viewer.getUniqueId())||!viewer.getOpenInventory().getTitle().equals(title))return;updateGui(viewer,target,sessions.getOrDefault(target.getUniqueId(),s),viewer.getOpenInventory().getTopInventory());},getConfig().getLong("gui.refresh-interval-ticks",1),getConfig().getLong("gui.refresh-interval-ticks",1));}
  private void updateGui(Player v,Player p,Session s,Inventory inv){ItemStack a=item(Material.BOOK,"gui.normal-info.name",List.of("§fName: "+p.getName(),"§fRank: "+rank(p),"§fToday: "+dur(s.todayActive),"§fWeek: "+dur(s.weekActive),"§fMonth: "+dur(s.monthActive),"§fTotal: "+dur(s.active)));ItemStack b=item(Material.WRITABLE_BOOK,"gui.detailed-info.name",List.of("§fName: "+p.getName(),"§fUUID: "+p.getUniqueId(),"§6Playtime", "§fToday: "+dur(s.todayActive),"§fWeek: "+dur(s.weekActive),"§fMonth: "+dur(s.monthActive),"§fTotal: "+dur(s.active),"§6AFK", "§fToday: "+dur(s.todayAfk),"§fWeek: "+dur(s.weekAfk),"§fMonth: "+dur(s.monthAfk),"§fTotal: "+dur(s.afk)));Gui g=guis.get(v.getUniqueId());if(g!=null){if(g.normal<inv.getSize())inv.setItem(g.normal,a);if(g.detailed<inv.getSize())inv.setItem(g.detailed,b);}}
  private ItemStack item(Material m,String path,List<String> lore){String mat=getConfig().getString(path.replace("name","material"),m.name());try{m=Material.valueOf(mat.toUpperCase());}catch(Exception ignored){}ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();x.setDisplayName(color(getConfig().getString(path,"&eInformation")));x.setLore(lore);i.setItemMeta(x);return i;}
  private boolean zoneCommand(CommandSender s,String[] a){if(a.length<1){s.sendMessage("§e/afkzone create|delete|list|info|setpos1|setpos2|setreward|setprotection <name>");return true;}String sub=a[0].toLowerCase();if(sub.equals("list")){s.sendMessage("§6Zones: §f"+String.join(", ",zones.keySet()));return true;}if(a.length<2)return true;String name=a[1];if(sub.equals("create")){zones.put(name,new Zone(name,"world",0,0,0,0,0,0,true,true));saveZone(zones.get(name));s.sendMessage("§aZone created; set positions.");}else if(sub.equals("delete")){zones.remove(name);try(PreparedStatement q=db.prepareStatement("DELETE FROM zones WHERE name=?")){q.setString(1,name);q.executeUpdate();}catch(Exception ignored){}}else if(sub.startsWith("setpos")&&s instanceof Player p){ZonePos x=new ZonePos(p.getWorld().getName(),p.getLocation().getBlockX(),p.getLocation().getBlockY(),p.getLocation().getBlockZ());if(sub.equals("setpos1"))p1=x;else p2=x;if(p1!=null&&p2!=null)saveZone(new Zone(name,p1.world,Math.min(p1.x,p2.x),Math.max(p1.x,p2.x),Math.min(p1.y,p2.y),Math.max(p1.y,p2.y),Math.min(p1.z,p2.z),Math.max(p1.z,p2.z),true,true));}else if((sub.equals("setreward")||sub.equals("setprotection"))&&a.length>2){Zone z=zones.get(name);if(z!=null){boolean v=Boolean.parseBoolean(a[2]);saveZone(new Zone(z.name,z.world,z.minX,z.maxX,z.minY,z.maxY,z.minZ,z.maxZ,sub.equals("setreward")?v:z.rewards,sub.equals("setprotection")?v:z.protection));}}return true;}
  private void saveZone(Zone z){zones.put(z.name,z);try(PreparedStatement q=db.prepareStatement("INSERT OR REPLACE INTO zones VALUES(?,?,?,?,?,?,?,?,?,?)")){q.setString(1,z.name);q.setString(2,z.world);q.setInt(3,z.minX);q.setInt(4,z.maxX);q.setInt(5,z.minY);q.setInt(6,z.maxY);q.setInt(7,z.minZ);q.setInt(8,z.maxZ);q.setBoolean(9,z.rewards);q.setBoolean(10,z.protection);q.executeUpdate();}catch(Exception e){getLogger().warning(e.getMessage());}}
  @Override public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){String n=c.getName().toLowerCase();if(n.equals("info")||n.equals("detailinfo")||n.equals("guiinfo")){if(a.length==1)return names(a[0]);return List.of();}if(n.equals("activity"))return a.length==1?prefix(a[0],List.of("top","winners","reload","reset","resetweek","forcewin")):a.length==2&&(a[0].equals("reset")||a[0].equals("forcewin"))?names(a[1]):List.of();if(n.equals("afkzone")){if(a.length==1)return prefix(a[0],List.of("create","delete","list","info","setpos1","setpos2","setreward","setprotection"));if(a.length==2&& !a[0].equals("create"))return prefix(a[1],zones.keySet());if(a.length==3&&(a[0].equals("setreward")||a[0].equals("setprotection")))return prefix(a[2],List.of("true","false"));}return List.of();}
  private List<String> names(String x){List<String> r=new ArrayList<>();for(Player p:Bukkit.getOnlinePlayers())if(p.getName().toLowerCase().startsWith(x.toLowerCase()))r.add(p.getName());return r;}private List<String> prefix(String x,Collection<String> c){return c.stream().filter(v->v.toLowerCase().startsWith(x.toLowerCase())).toList();}
  private String rank(Player p){return chat==null?"Member":Optional.ofNullable(chat.getPlayerPrefix(p)).filter(x->!x.isBlank()).orElse("Member");}private String dur(long s){long h=s/3600,m=s%3600/60,sec=s%60;return h>0?h+"h "+m+"m "+sec+"s":m>0?m+"m "+sec+"s":sec+"s";}private String color(String s){return ChatColor.translateAlternateColorCodes('&',s==null?"":s);}private void msg(CommandSender s,String k,Map<String,String> p){String x=messages.getString(k,k);for(var e:p.entrySet())x=x.replace("["+e.getKey()+"]",e.getValue());s.sendMessage(color(messages.getString("prefix","")+x));}private ZonePos pos(String w,int x,int y,int z){return new ZonePos(w,x,y,z);}private ZonePos p1(){return p1;}private String tz(){return getConfig().getString("timezone","UTC");}private String place(String c,Player p,Session s,int position,String week){return c.replace("[player]",p.getName()).replace("[uuid]",p.getUniqueId().toString()).replace("[rank]",rank(p)).replace("[playtime]",dur(s.active)).replace("[afktime]",dur(s.afk)).replace("[week]",week).replace("[position]",String.valueOf(position));}private void dispatchWinner(Player p,String id){try(PreparedStatement q=db.prepareStatement("UPDATE winners SET status='CLAIMED' WHERE id=? AND status='PENDING'")){q.setString(1,id);q.executeUpdate();}catch(Exception ignored){}}
  @Override public void onDisable(){for(Session s:sessions.values())save(s);try{if(db!=null)db.close();}catch(Exception ignored){}guis.clear();}
}
